api/urls.py
from django.urls import path

from .views import PostListViews

urlpatterns = [
    path('list/', PostListViews.as_view())
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap

from post.sitemaps import PostSitemap

sitemaps = {
    'post': PostSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls')),
    path('aut/', include('account.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('api/', include('api.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path


from .views import post_list, post_detail, post_comment, search_post
from .feeds import LatestPostsFeed

app_name = 'post'

urlpatterns = [
    path('', post_list, name='post_list'),
    path('dt/<slug:slug>/', post_detail, name='post_detail'),
    path('<int:post_id>/comment/', post_comment, name='post_comment'),
    path('tag/<slug:tag_slug>/', post_list, name='post_list_by_tag'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', search_post, name='post_search'),

]

post/models.py
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from taggit.managers import TaggableManager

from django.db import models


class PublishedManager(models.Manager):
    """
    мениджер для модели постов, упорядовающий результат
    запроса по поле даты
    """
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)





class Post(models.Model):
    """
    модель для постов
    """


    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(verbose_name="нозывание", max_length=250)
    slug = models.SlugField(verbose_name="слаг", max_length=250, )
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField(verbose_name="текст статьи")
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)

    tags = TaggableManager()

    objects = models.Manager()  # менеджер, применяемый по умолчанию
    published = PublishedManager()  # конкретно-прикладной менеджер

    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post:post_detail', args=[self.slug])





class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [models.Index(fields=['created']), ]

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

post/forms.py
from django import forms

from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']

class SearchForm(forms.Form):
    query = forms.CharField()

post/views.py
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count
from django.shortcuts import render, get_object_or_404
from django.views.decorators.http import require_POST
from taggit.models import Tag
from django.contrib.postgres.search import TrigramSimilarity

from .models import Post, Comment
from .forms import CommentForm, EmailPostForm, SearchForm

def post_list(request, tag_slug=None):
    post_list = Post.objects.all()

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])
    paginator = Paginator(post_list, 3)
    page_number = request.GET.get('page', 1)

    try:
        posts = paginator.page(page_number)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        posts = paginator.page(1)
    return render(request, 'post/index.html', {'posts': posts, 'tag': tag})


def post_detail(request, slug):
    post = get_object_or_404(Post, slug=slug)

    comments = post.comments.filter(active=True)

    form = CommentForm()

    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.objects.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
    return render(request, template_name='post/detail.html', context={'post': post,
                                                                      'comments': comments,
                                                                      'form': form,
                                                                      'similar_posts': similar_posts})

@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    comment = None
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()

    return render(request, 'post/comment.html', {'post': post, 'form': form, 'comment': comment})




def search_post(request):
    form = SearchForm()
    query = None
    results = []
    search_get = 0

    if 'query' in request.GET:
        form = SearchForm(request.GET)
        search_get = request.GET
        if form.is_valid():
            query = form.cleaned_data['query']
            # results = Post.objects.annotate(
            #     similarity=TrigramSimilarity('title', query)
            # ).filter(similarity__gt=0.1).order_by('-similarity')

            search_vector = SearchVector('title', 'body')
            search_query = SearchQuery(query)
            results = Post.objects.annotate(
                search=search_vector,
                rank=SearchRank(search_vector, search_query)
            ).filter(search=search_query).order_by('-rank')



    return render(request, 'post/search.html', {'form': form, 'query': query, 'results': results,'search_get': search_get})


















# def send_email(request, post_id):
#     post = get_object_or_404(Post, pk=post_id)
#     send = False
#     if request.method == 'POST':
#         form = EmailPostForm(request.POST)
#         if form.is_valid():
#             sd = form.cleaned_data
#             post_url = request.build_absolute_uri(post.get_absolute_url())
#             subject = ''

post/templates/post/comment.html
{% extends "base.html" %}
{% block title %}Add a comment{% endblock %}
{% block content %}
    {% if comment %}
         <h2>Your comment has been added.</h2>
        <p><a href="{{ post.get_absolute_url }}">Back to the post</a></p>
    {% else %}
        {% include "post/includes/comment_form.html" %}
    {% endif %}
{% endblock %}

post/templates/post/detail.html
{% extends "base.html" %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}

<h1>{{ post.title }}</h1>
<p class="date">
    Published {{ post.publish }} by {{ post.author }}
</p>
<p>
{{ post.body|truncatewords:200|linebreaks }}
</p>

<h2>Другие посты</h2>
   {% for post in posts %}
      <p>
          <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
      </p>
  {% empty %}
   There are no similar posts yet.
{% endfor %}


{% with comments.count as total_comments %}
    <h2>
        {{ total_comments }} comment{{ total_comments|pluralize }}
    </h2>
*****************{{total_comments }}********************
{% endwith %}



{% for comment in comments %}
   <div class="comment">
       <p class="info">
        Comment {{ forloop.counter }} by {{ comment.name }}
        {{ comment.created }}
   </div>
{% empty %}
    <p>Коменнтарий к посту нет.</p>
{% endfor %}
    
    {% include "post/includes/comment_form.html" %}


<h4>похожие посты</h4>
{% for s_p in similar_posts %}
   <div class="similar_posts">

       <a href="{{ post.get_absolute_url }}">{{ s_p.title }}</a>
   </div>
{% empty %}
    <p>Коменнтарий к посту нет.</p>
{% endfor %}
{% endblock %}

post/templates/post/index.html
{% extends "base.html" %}
{% block title %}My Blog{% endblock %}
{% block content %}
<h1>My Blog</h1>



{% for post in posts %}

     <h1>
     <a href="{{ post.get_absolute_url }}">
          {{ post.title }}
    </a>
         </h1>

<p class="tags">
Tags:
   {% for tag in post.tags.all %}
   <a href="{% url 'post:post_list_by_tag' tag.slug %}">
   {{ tag.name }}
</a>
{% if not forloop.last %}, {% endif %}
{% endfor %}
</p>
{{ post.body|truncatewords:30|linebreaks }}
{% endfor %}

{% include 'post/pagination.html' with page=posts %}
{% endblock %}

post/templates/post/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">назад</a>
        {% endif %}
        <span class="current">
            страница {{ page.number }} от {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">далее</a>
        {% endif %}
    </span>
</div>

post/templates/post/search.html
{% extends "base.html" %}

{% block title %}Поиск{% endblock %}
{% block content %}
{% if query %}
<h1> по запросу "{{ query }}"</h1>
<h3>
    {% with results.count as total_results %}
    найден {{ total_results }} результат
    {% endwith %}
</h3>
{% for post in results %}
<h4>
    <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
    </a>
</h4>
{{ post.body}}
<h3>{{search_get}}</h3>
{% empty %}
<p>по этому зопросу результат не нойден</p>
{% endfor %}
<p><a href="{% url "post:post_search" %}">Повторить попытку снова</a></p>
{% else %}
<h1>Слова для поиска</h1>
<form method="get">
    {{ form.as_p }}
    <input type="submit" value="Search">
</form>

{% endif %}
{% endblock %}